services:
  - type: web
    name: payment-gateway-api
    env: node
    buildCommand: npm install && npm run build:render
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: PAYSTACK_SECRET_KEY
        sync: false
      - key: PAYSTACK_BASE_URL
        value: https://api.paystack.co