name: AGRICON CD.

on:
  push:
    branches: [ dev, main ]
  pull_request:
    branches: [ dev, main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['lts/*']

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - run: npm ci
    - run: npm run build
    - run: npm test  

    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: production-artifacts
        path: |
          dist/
          package.json
          package-lock.json

  deploy-to-render:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Deploy to Render
      uses: johnbeynon/render-deploy-action@v0.0.8
      # with:
      #   service-id: ${{ secrets.RENDER_SERVICE_ID }}
      #   api-key: ${{ secrets.RENDER_API_KEY }}